repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - modules/nf-core/cellrangeratac/mkref/meta.yml
    - modules/nf-core/cellrangeratac/mkref/main.nf
    - assets/*.png
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - assets/multiqc_config.yml
  correct_meta_inputs:
    - modules/nf-core/cellrangeratac/mkref/meta.yml
  modules:
    cellrangeratac/mkref:
      - all_tests

template:
  org: nf-core
  name: genomeprep
  description: A pipeline to prepare reference genomes and annotations for non-model organisms.
  author: Leandro Tiburske
  version: 3.4.1
  force: true
  outdir: .
  skip_features:
    - multiqc
    - fastqc
  is_nfcore: true
