lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/multiqc_config.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Leandro Tiburske
  description: A pipeline to prepare reference genomes and annotations for non-model
    organisms.
  force: false
  is_nfcore: true
  name: genomeprep
  org: nf-core
  outdir: .
  skip_features:
    - multiqc
    - fastqc
  version: 1.0.0dev
