name: cellrangeratac_mkref
description: Module to build the reference needed by the 10x Genomics Cell Ranger
  ATAC tool. Uses the cellranger-atac mkref command.
keywords:
  - reference
  - mkref
  - index
tools:
  - cellranger-atac:
      description: Cell Ranger ATAC is a set of analysis pipelines that process Chromium
        Single Cell ATAC data.
      homepage: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/what-is-cell-ranger-atac
      documentation: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/what-is-cell-ranger-atac
      tool_dev_url: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/what-is-cell-ranger-atac
      licence: ["10x Genomics EULA"]
      identifier: ""
input:
  - fasta:
      type: file
      description: Reference genome FASTA file
      pattern: "*.{fasta,fa}"
      ontologies: []
  - gtf:
      type: file
      description: Reference transcriptome GTF file
      pattern: "*.gtf"
      ontologies: []
  - organism:
      type: string
      description: Organism name (e.g., "Homo sapiens")
      pattern: .+
  - genome_name:
      type: string
      description: Name of the reference genome (e.g., "GRCh38")
      pattern: .+
  - non_nuclear_contigs:
      type: list
      description: List of non-nuclear contigs to include (e.g., ["chr1", "chr2"])
      items:
        type: string
  - transcription_factors:
      type: file
      description: Sequence motif file (e.g., of transcription factors)
      pattern: "*.txt"
      ontologies: []
  - reference_name:
      type: string
      description: The name to give the new reference folder
      pattern: .+
output:
  reference:
    - ${reference_name}:
        type: directory
        description: Folder called regarding reference_name containing all the reference
          indices needed by Cell Ranger ATAC
  versions:
    - versions.yml:
        type: file
        description: File containing software version
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@ggabernet"
  - "@heylf"
maintainers:
  - "@ggabernet"
  - "@heylf"
